routes/web.php
		|--------------------------------------------------------------------------
		| Route Fasilitas
		|--------------------------------------------------------------------------
		*/
		Route::prefix('/fasilitas')->group(function(){
			/*
			|--------------------------------------------------------------------------
			| Route Pengaduan
			|--------------------------------------------------------------------------
			*/
			Route::get('/pengaduan', 'Backend\PengaduanController@index')->name('fasilitas.pengaduan');

		
			/*
			|--------------------------------------------------------------------------
			| Route Layanan
			|--------------------------------------------------------------------------
			*/
			Route::prefix('/layanan')->group(function(){
				Route::get('/', 'Backend\LayananController@index')->name('fasilitas.layanan.index');
				Route::get('/data', 'Backend\LayananController@layanan_data')->name('fasilitas.layanan.data');
				Route::get('/tambah', 'Backend\LayananController@layanan_tambah')->name('fasilitas.layanan.tambah');
				Route::post('/simpan', 'Backend\LayananController@layanan_simpan')->name('fasilitas.layanan.simpan');
				Route::get('/detail/{id}', 'Backend\LayananController@layanan_detail')->name('fasilitas.layanan.detail');
				Route::post('/update/{id}', 'Backend\LayananController@layanan_update')->name('fasilitas.layanan.update');
				Route::get('/hapus/{id}', 'Backend\LayananController@layanan_hapus')->name('fasilitas.layanan.hapus');
			});
		});

		/*
		|--------------------------------------------------------------------------
		| Route Website Kabar Berita
		|--------------------------------------------------------------------------
		*/
		Route::prefix('/website')->group(function(){
			/*
			|--------------------------------------------------------------------------
			| Route Konfigurasi Web
			|--------------------------------------------------------------------------
			*/
			Route::get('/konfigurasi', 'Backend\WebconfigController@index')->name('website.webconfig');
			/*
			|--------------------------------------------------------------------------
			| Route Berita
			|--------------------------------------------------------------------------
			*/
			Route::prefix('/berita')->group(function(){
				Route::get('/', 'Backend\BeritaController@index')->name('website.berita');
				Route::get('/data', 'Backend\BeritaController@berita_data')->name('berita.data');
				Route::get('/tambah', 'Backend\BeritaController@berita_tambah')->name('berita.tambah');
				Route::post('/simpan', 'Backend\BeritaController@berita_simpan')->name('berita.simpan');
				Route::get('/detail/{id}', 'Backend\BeritaController@berita_detail')->name('berita.detail');
				Route::post('/update/{id}', 'Backend\BeritaController@berita_update')->name('berita.update');
				Route::get('/hapus/{id}', 'Backend\BeritaController@berita_hapus')->name('berita.hapus');
				
				/*
				|--------------------------------------------------------------------------
				| Route Kategori Berita
				|--------------------------------------------------------------------------
				*/
				Route::prefix('/kategori')->group(function(){
					Route::get('/', 'Backend\KategoriberitaController@index')->name('website.berita.kategori');
					Route::get('/data', 'Backend\KategoriberitaController@kategori_data')->name('website.berita.kategori.data');
					Route::post('/simpan', 'Backend\KategoriberitaController@kategori_simpan')->name('website.berita.kategori.simpan');
					Route::get('/detail/{id}', 'Backend\KategoriberitaController@kategori_detail')->name('website.berita.kategori.detail');
					Route::post('/update/{id}', 'Backend\KategoriberitaController@kategori_update')->name('website.berita.kategori.update');
					Route::get('/hapus/{id}', 'Backend\KategoriberitaController@kategori_hapus')->name('website.berita.kategori.hapus');
					Route::prefix('/sub')->group(function(){
						Route::get('/', 'Backend\KategoriberitaSubController@index')->name('website.berita.kategori.sub');
						Route::get('/data', 'Backend\KategoriberitaSubController@sub_kategori_data')->name('website.berita.kategori.sub.data');
						Route::post('/simpan', 'Backend\KategoriberitaSubController@sub_kategori_simpan')->name('website.berita.kategori.sub.simpan');
						Route::get('/detail/{id}', 'Backend\KategoriberitaSubController@sub_kategori_detail')->name('website.berita.kategori.sub.detail');
						Route::post('/update/{id}', 'Backend\KategoriberitaSubController@sub_kategori_update')->name('website.berita.kategori.sub.update');
						Route::get('/hapus/{id}', 'Backend\KategoriberitaSubController@sub_kategori_hapus')->name('website.berita.kategori.sub.hapus');
					});
				});
				
				/*
				|--------------------------------------------------------------------------
				| Route Banner Berita
				|--------------------------------------------------------------------------
				*/
				Route::prefix('/banner')->group(function(){
					Route::get('/', 'Backend\BannerController@banner_index')->name('website.berita.banner');
					Route::get('/data', 'Backend\BannerController@banner_data')->name('website.berita.banner.data');
					Route::post('/simpan', 'Backend\BannerController@banner_simpan')->name('website.berita.banner.simpan');
					Route::get('/detail/{id}', 'Backend\BannerController@banner_detail')->name('website.berita.banner.detail');
					Route::post('/update/{id}', 'Backend\BannerController@banner_update')->name('website.berita.banner.update');
					Route::get('/hapus/{id}', 'Backend\BannerController@banner_hapus')->name('website.berita.banner.hapus');
				});


				/*
				|--------------------------------------------------------------------------
				| Route Tag Berita
				|--------------------------------------------------------------------------
				*/
				Route::prefix('/tag')->group(function(){
					Route::get('/', 'Backend\TagController@index')->name('website.berita.tag');
					Route::get('/data', 'Backend\TagController@tag_data')->name('website.berita.tag.data');
					Route::post('/simpan', 'Backend\TagController@tag_simpan')->name('website.berita.tag.simpan');
					Route::get('/detail/{id}', 'Backend\TagController@tag_detail')->name('website.berita.tag.detail');
					Route::post('/update/{id}', 'Backend\TagController@tag_update')->name('website.berita.tag.update');
					Route::get('/hapus/{id}', 'Backend\TagController@tag_hapus')->name('website.berita.tag.hapus');
				});
			});
		});

		/*
		|--------------------------------------------------------------------------
		| Route Pengaturan App
		|--------------------------------------------------------------------------
		*/
		Route::prefix('/pengaturan')->group(function(){
			/*
			|--------------------------------------------------------------------------
			| Route Pengguna App
			|--------------------------------------------------------------------------
			*/
			Route::get('/pengguna', 'Backend\PenggunaController@index')->name('pengaturan.pengguna');
			Route::post('/pengguna/update/{id}', 'Backend\PenggunaController@pengguna_update')->name('pengguna.update');

			/*
			|--------------------------------------------------------------------------
			| Route Manajemen File
			|--------------------------------------------------------------------------
			*/
			Route::get('/manajerfile', 'Backend\ManajerfileController@index')->name('pengaturan.file');
		});

		/*
		|--------------------------------------------------------------------------
		| Route Manajemen Desa
		|--------------------------------------------------------------------------
		*/
		Route::prefix('/manajemen')->group(function(){
			Route::prefix('/desa')->group(function(){
				Route::get('/', 'Backend\DesaController@index')->name('manajemen.desa.index');
				Route::get('/data', 'Backend\DesaController@desa_data')->name('manajemen.desa.data');
				Route::get('/tambah', 'Backend\DesaController@desa_tambah')->name('manajemen.desa.tambah');
				Route::post('/simpan', 'Backend\DesaController@desa_simpan')->name('manajemen.desa.simpan');
				Route::get('/detail/{id}', 'Backend\DesaController@desa_detail')->name('manajemen.desa.detail');
				Route::get('/show/{id}', 'Backend\DesaController@desa_show')->name('manajemen.desa.show');
				Route::post('/update/{id}', 'Backend\DesaController@desa_update')->name('manajemen.desa.update');
				Route::get('/hapus/{id}', 'Backend\DesaController@desa_hapus')->name('manajemen.desa.hapus');
			});
		});


});

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
*/
Route::get('/', function () {
    return view('auth.login');
});
Route::prefix('/')->group(function () {
	Route::name('frontpage.')->group(function () {
		Route::get('/', 'Frontend\IndexController@frontpage_index')->name('index');
		Route::get('profil','Frontend\IndexController@frontpage_profil')->name('profil');
		
		Route::prefix('/potensi')->group(function () {
			Route::get('/','Frontend\IndexController@frontpage_potensi')->name('potensi');
			Route::get('/detail/{potensi_slug}', 'Frontend\IndexController@detail_potensi')->name('detail_potensi');
		});
		
		Route::get('layanan','Frontend\IndexController@frontpage_layanan')->name('layanan');
		Route::get('layanan/detail/{id_desa}/{slug}','Frontend\IndexController@frontpage_layanan_detail')->name('layanan.detail');

		Route::get('lapor','Frontend\IndexController@frontpage_lapor')->name('lapor');
		
		Route::prefix('/info')->group(function () {
			Route::get('/','Frontend\IndexController@frontpage_info')->name('info');
			Route::get('/detail','Frontend\IndexController@frontpage_info_detail')->name('info-detail');
		});
		
		Route::prefix('/berita')->name('berita.')->group(function () {
			Route::get('/','Frontend\IndexController@frontpage_berita')->name('index');
			Route::get('/detail/{id_desa}/{slug}','Frontend\IndexController@frontpage_berita_detail')->name('post.detail');
		});

app/Http/Controllers/Frontend/IndexController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Desa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class IndexController extends Controller
{
    public function frontpage_index ()
    {
        return view('frontend.index');
    }

    public function frontpage_profil()
    {
        return view('frontend.profil');
    }

    public function frontpage_potensi()
    {
        return view('frontend.potensi');
    }

    public function detail_potensi($slug)
    {
        // $data = \App\Models\Potensi::
        // leftjoin('desa','potensi_desa.id_desa','desa.id_desa')
        // ->where('potensi_desa.slug_potensi', '=', $slug)
        // ->first();
        $data = DB::table('potensi_desa AS p_desa')
            ->select('p_desa.*')
            ->leftjoin('desa','p_desa.id_desa','desa.id_desa')
            ->where('p_desa.slug_potensi', '=', $slug)
            ->first();
        return view('frontend.potensi-detail')->with([
            'detail' => $data
        ]);
    }
    
    public function frontpage_layanan()
    {
        return view('frontend.layanan');
    }

    public function frontpage_lapor()
    {
        return view('frontend.lapor');
    }    
    
    public function frontpage_info()
    {
        return view('frontend.informasi');
    }

    public function frontpage_info_detail()
    {
        return view('frontend.informasi-detail');
    }

    public function frontpage_berita ()
    {
        // $desa = Desa::
        return view('frontend.informasi');
    }

    public function frontpage_berita_detail ()
    {
        return view('frontend.informasi');
    }
}

resources/views/frontend/index.blade.php
<script>
function redirect(domain) {
    window.location.href = domain;
}
</script>
@php
    // if(\Request::segment(1)=="login"){
        $get_domain = \Request::getSchemeAndHttpHost();
        // print_r($get_domain);
        // print_r(explode("://",$get_domain));
        // print_r(explode("://",$get_domain)[1]);
        $explode = explode("://",$get_domain);
        $current = $explode[1];

        $check = \App\Models\Desa::where('website', $current)->first();

        // dd($check);
        if(empty($check)){
            echo "<script>redirect('".$get_domain."/login');</script>";
        }
    // }
@endphp
@extends('frontend.layouts.app')
@section('page_title')
Halaman Depan
@endsection
@section('content')
{!! \Helpers::jumbotron(\Request::getHttpHost()) !!}
<div class="home-intro home-intro-quaternary" id="home-intro">
    <div class="container">
        <div class="row text-center">
            <div class="col">
                <p class="mb-0">
                        Transparansi dana desa merupakan bentuk pengawasan penggunaan dan 
                        pengolalaan anggaran pendapatan dan belanja desa, 
                        serta sebagai sosialisasi dan wadah penerapan program "Padat Karya".
                        {{-- <span class="highlighted-word highlighted-word-animation-1 highlighted-word-animation-1-light text-color-light font-weight-semibold text-5">
                            
                        </span> --}}
                    <span>Yuk! Kita periksa transparansi dana desa.</span>
                </p>
            </div>
        </div>
    </div>
</div>

{{-- Section transparansi dana desa--}}
{!! \Helpers::dana_desa() !!}

{{-- Section blog post --}}

<div class="container container-lg">
    <div class="row py-5">
        <div class="col-md-6 col-lg-4">
            <h3 class="font-weight-bold text-3 mb-0">Populer</h3>
            {!! \Helpers::blog_post_popular(\Request::getHttpHost()) !!}
        </div>
        <div class="col-md-6 col-lg-4">
            <h3 class="font-weight-bold text-3 mb-0">Terbaru</h3>
            {!! \Helpers::blog_post_recent(\Request::getHttpHost()) !!}
        </div>
        <div class="col-lg-4">
            <h3 class="font-weight-bold text-3 mt-4 mt-md-0">Unggulan</h3>
            {!! \Helpers::blog_post_featured(\Request::getHttpHost()) !!}
        </div>
    </div>    
</div>

{{-- Section galery & potention --}}
<section class="section bg-color-light border-0 pb-0 m-0">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center appear-animation" data-appear-animation="fadeInUpShorter">
                <h2 class="font-weight-normal text-6 pb-2 mb-4"><strong class="font-weight-extra-bold">Produk</strong>
                    &amp; <strong class="font-weight-extra-bold">Potensi Desa</strong></h2>
            </div>
        </div>
    </div>
    <div class="image-gallery sort-destination full-width mb-0">
        {!! \Helpers::potensi_desa(\Request::getHttpHost()) !!}
        
        {{-- <div class="isotope-item">
            <div class="image-gallery-item mb-0 appear-animation" data-appear-animation="fadeInLeftShorter"
                data-appear-animation-delay="700">
                <a href="#">
                    <span class="thumb-info thumb-info-centered-info thumb-info-no-borders">
                        <span class="thumb-info-wrapper">
                            <img src="{{asset('img/projects/project-30.jpg')}}" class="img-fluid" alt="">
                            <span class="thumb-info-title">
                                <span class="thumb-info-inner">Project Title</span>
                                <span class="thumb-info-type">Project Type</span>
                            </span>
                            <span class="thumb-info-action">
                                <span class="thumb-info-action-icon"><i class="fas fa-plus"></i></span>
                            </span>
                        </span>
                    </span>
                </a>
            </div>
        </div>
        <div class="isotope-item">
            <div class="image-gallery-item mb-0 appear-animation" data-appear-animation="fadeInLeftShorter"
                data-appear-animation-delay="500">
                <a href="#">
                    <span class="thumb-info thumb-info-centered-info thumb-info-no-borders">
                        <span class="thumb-info-wrapper">
                            <img src="{{asset('img/projects/project-31.jpg')}}" class="img-fluid" alt="">
                            <span class="thumb-info-title">
                                <span class="thumb-info-inner">Project Title</span>
                                <span class="thumb-info-type">Project Type</span>
                            </span>
                            <span class="thumb-info-action">
                                <span class="thumb-info-action-icon"><i class="fas fa-plus"></i></span>
                            </span>
                        </span>
                    </span>
                </a>
            </div>
        </div>
        <div class="isotope-item">
            <div class="image-gallery-item mb-0 appear-animation" data-appear-animation="fadeIn"
                data-appear-animation-delay="300">
                <a href="#">
                    <span class="thumb-info thumb-info-centered-info thumb-info-no-borders">
                        <span class="thumb-info-wrapper">
                            <img src="{{asset('img/projects/project-32.jpg')}}" class="img-fluid" alt="">
                            <span class="thumb-info-title">
                                <span class="thumb-info-inner">Project Title</span>
                                <span class="thumb-info-type">Project Type</span>
                            </span>
                            <span class="thumb-info-action">
                                <span class="thumb-info-action-icon"><i class="fas fa-plus"></i></span>
                            </span>
                        </span>
                    </span>
                </a>
            </div>
        </div>
        <div class="isotope-item">
            <div class="image-gallery-item mb-0 appear-animation" data-appear-animation="fadeInRightShorter"
                data-appear-animation-delay="500">
                <a href="#">
                    <span class="thumb-info thumb-info-centered-info thumb-info-no-borders">
                        <span class="thumb-info-wrapper">
                            <img src="{{asset('img/projects/project-33.jpg')}}" class="img-fluid" alt="">
                            <span class="thumb-info-title">
                                <span class="thumb-info-inner">Project Title</span>
                                <span class="thumb-info-type">Project Type</span>
                            </span>
                            <span class="thumb-info-action">
                                <span class="thumb-info-action-icon"><i class="fas fa-plus"></i></span>
                            </span>
                        </span>
                    </span>
                </a>
            </div>
        </div>
        <div class="isotope-item">
            <div class="image-gallery-item mb-0 appear-animation" data-appear-animation="fadeInRightShorter"
                data-appear-animation-delay="700">
                <a href="#">
                    <span class="thumb-info thumb-info-centered-info thumb-info-no-borders">
                        <span class="thumb-info-wrapper">
                            <img src="{{asset('img/projects/project-34.jpg')}}" class="img-fluid" alt="">
                            <span class="thumb-info-title">
                                <span class="thumb-info-inner">Project Title</span>
                                <span class="thumb-info-type">Project Type</span>
                            </span>
                            <span class="thumb-info-action">
                                <span class="thumb-info-action-icon"><i class="fas fa-plus"></i></span>
                            </span>
                        </span>
                    </span>
                </a>
            </div>
        </div> --}}
    </div>
</section>

{{-- Section supporter --}}
<div class="container">
    <div class="row py-5 my-5">
        <div class="col">
            <div class="owl-carousel owl-theme mb-0"
                data-plugin-options="{'responsive': {'0': {'items': 1}, '476': {'items': 1}, '768': {'items': 5}, '992': {'items': 7}, '1200': {'items': 7}}, 'autoplay': true, 'autoplayTimeout': 3000, 'dots': false}">
                <div>
                    <img class="img-fluid opacity-2" src="{{asset('img/logos/logo-1.png')}}" alt="">
                </div>
                <div>
                    <img class="img-fluid opacity-2" src="{{asset('img/logos/logo-2.png')}}" alt="">
                </div>
                <div>
                    <img class="img-fluid opacity-2" src="{{asset('img/logos/logo-3.png')}}" alt="">
                </div>
                <div>
                    <img class="img-fluid opacity-2" src="{{asset('img/logos/logo-4.png')}}" alt="">
                </div>
                <div>
                    <img class="img-fluid opacity-2" src="{{asset('img/logos/logo-5.png')}}" alt="">
                </div>
                <div>
                    <img class="img-fluid opacity-2" src="{{asset('img/logos/logo-6.png')}}" alt="">
                </div>
                <div>
                    <img class="img-fluid opacity-2" src="{{asset('img/logos/logo-4.png')}}" alt="">
                </div>
                <div>
                    <img class="img-fluid opacity-2" src="{{asset('img/logos/logo-2.png')}}" alt="">
                </div>
            </div>

        </div>
    </div>
</div>

@endsection
@section('css')
<link rel="stylesheet" href="{{asset('vendor/chartjs/Chart.min.css')}}">
@endsection
@section('javascript')
<script src="{{asset('vendor/chartjs/Chart.min.js')}}"></script>
<script type="text/javascript">
	$(function () { 
        var ctx = document.getElementById('chart_anggaran_desa').getContext('2d');
		var month = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
		var config = new Chart(ctx, {
			type: 'line',
			data: {
				labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
				datasets: [{
					label: 'Pendapatan Pertanian',
					backgroundColor: "red",
					borderColor: "red",
					data: [12, 19, 3, 5, 2, 3],
					fill: false,
				}, {
					label: 'Pamsimas',
					fill: false,
					backgroundColor: "blue",
					borderColor: "blue",
					data: [1,2,4,6,5,10,12,16],
				}]
			},
			options: {
				responsive: true,
				tooltips: {
					mode: 'index',
					intersect: false,
				},
				hover: {
					mode: 'nearest',
					intersect: true
				},
				scales: {
					xAxes: [{
						display: true,
						scaleLabel: {
							display: true,
							labelString: 'Bulan'
						}
					}],
					yAxes: [{
						display: true,
						scaleLabel: {
							display: true,
							labelString: 'Ratusan Ribu'
						}
					}]
				}
			}
        })
        $('.m-beranda').addClass('active')
    });
</script>
@endsection

resources/views/frontend/informasi-detail.blade.php
@extends('frontend.layouts.app')
@section('page_title')
Papan Informasi
@endsection
@section('content')
<div class="container py-4">
    <div class="row">
        <div class="col">
            <div class="blog-posts single-post">
                <article class="post post-large blog-single-post border-0 m-0 p-0">
                    <div class="post-date ml-0">
                        <span class="day">{{ date('d', strtotime($detail->beritaCreatedAt)) }}</span>
                        <span class="month">{{ date('M', strtotime($detail->beritaCreatedAt)) }}</span>
                    </div>
            
                    <div class="post-content ml-0">
                        <h2 class="font-weight-bold"><a href="">{{ $detail->judul_berita }}</a></h2>
                        <div class="post-meta">
                            <span><i class="far fa-user"></i> Penulis <a href="#">{{ $detail->get_desa->nama_desa}}</a> </span>
                            <span><i class="far fa-calendar-check"></i> {{ date('d F Y H:i', strtotime($detail->beritaCreatedAt)) }}</span>
                            <span><i class="far fa-folder"></i> <a href="kategori/{{$detail->get_kategori_berita->slug_kategori}}">{{ $detail->get_kategori_berita->nama_kategori }}</a> </span>
                        </div>
                        <img src="{{ (!empty($detail->post_img)?asset('storage/images/berita/'.$detail->id_desa.'/'.$detail->post_img):asset('storage/images/berita/default.jpg')) }}" class="img-fluid float-left mr-4 mt-2" alt="">
                        {!! $detail->isi_berita !!}
                        <hr>
                        <div class="post-block mt-5 post-share">
                            <h4 class="mb-3">Bagikan artikel ini</h4>
                                        
                            <!-- AddThis Button BEGIN -->
                            <div class="addthis_toolbox addthis_default_style ">
                                <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
                                <a class="addthis_button_tweet"></a>
                                <a class="addthis_button_pinterest_pinit"></a>
                                <a class="addthis_counter addthis_pill_style"></a>
                            </div>
                            <!-- AddThis Button END -->
                           
                        </div>
                        {{-- <div class="post-block mt-4 pt-2 post-author">
                            <h4 class="mb-3">Author</h4>
                            <div class="img-thumbnail img-thumbnail-no-borders d-block pb-3">
                                <a href="blog-post.html">
                                    <img src="img/avatars/avatar.jpg" alt="">
                                </a>
                            </div>
                            <p><strong class="name"><a href="#" class="text-4 pb-2 pt-2 d-block">John Doe</a></strong></p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim ornare nisi, vitae mattis nulla ante id dui. </p>
                        </div> --}}
                    </div>
                </article>
            </div>
        </div>
    </div>
</div>
@endsection
@section('css')

@endsection
@section('javascript')
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-50faf75173aadc53"></script>
<script type="text/javascript">
	$(function () { 
        $('.m-beranda').removeClass('active')
        $('.m-info').addClass('active')
    });
</script>
@endsection

resources/views/frontend/potensi-detail.blade.php
@extends('frontend.layouts.app')
@section('page_title')
Potensi Desa
@endsection
@section('content')
<section class="page-header page-header-modern bg-color-light-scale-1 page-header-md ">
    <div class="container-fluid">
        <div class="row align-items-center">

            <div class="col">
                <div class="row">
                    <div class="col-md-12 align-self-center p-static order-2 text-center">
                        <div class="overflow-hidden pb-2">
                            <h1 class="text-dark font-weight-bold text-9 appear-animation" data-appear-animation="maskUp" data-appear-animation-delay="100">{{$detail->nama_potensi}}</h1>
                            <span class="sub-title text-dark" data-appear-animation="maskUp" data-appear-animation-delay="100">{{Str::substr($detail->deskripsi_potensi,0,86)}} ...</span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<div class="container py-2">
    <div class="row">
        <div class="col">
            <div class="blog-posts single-post">           
                <article class="post post-large blog-single-post border-0 m-0 p-0">
                    <div class="post-date ml-0">
                        <span class="day">{{date('d',strtotime($detail->created_at))}}</span>
                        <span class="month">{{date('M',strtotime($detail->created_at))}}</span>
                    </div>
            
                    <div class="post-content ml-0">
            
                        <h2 class="font-weight-bold">
                            <a href="{{route('frontpage.detail_potensi',$detail->slug_potensi)}}">{{$detail->nama_potensi}}</a>
                        </h2>
            
                        <div class="post-meta">
                            <span><i class="far fa-user"></i> By <a href="#">John Doe</a></span>
                        </div>
                        <img src="/{{env('IMAGES_PATH')}}/potentions/{{$detail->id_desa}}/{{$detail->gambar}}" class="img-fluid float-left mr-4 mt-2" style="width:300px;height:200px;"/>
                        {{-- Content start --}}
                        {!! $detail->deskripsi_potensi !!}
                        {{-- End of content --}}
                        <div class="post-block mt-5 post-share">
                            <h4 class="mb-3">Bagikan</h4>
            
                            <!-- AddThis Button BEGIN -->
                            <div class="addthis_toolbox addthis_default_style ">
                                <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
                                <a class="addthis_counter addthis_pill_style"></a>
                            </div>
                            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-50faf75173aadc53"></script>
                            <!-- AddThis Button END -->
            
                        </div>
            
                        <div class="post-block mt-4 pt-2 post-author">
                            <h4 class="mb-3">Author</h4>
                            <div class="img-thumbnail img-thumbnail-no-borders d-block pb-3">
                                <a href="">
                                    <img src="{{asset('img/!logged-user.jpg')}}" alt="">
                                </a>
                            </div>
                            <p><strong class="name"><a href="#" class="text-4 pb-2 pt-2 d-block">John Doe</a></strong></p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim ornare nisi, vitae mattis nulla ante id dui. </p>
                        </div>
                    </div>
                </article>
            
            </div>
        </div>
    </div>

</div>
@endsection
@section('css')

@endsection
@section('javascript')
<script type="text/javascript">
	$(function () { 
        $('.m-beranda').removeClass('active')
        $('.m-potensi').addClass('active')
    });
</script>
@endsection